### ISSUE TITLE
Błędy

### ISSUE THREAD

**Issue by ghost** [kacperduras/ProtocolTab#8]
Podczas wyjścia z gry występuje taki błąd

`[20:29:02 WARN]: Exception in thread "Craft Scheduler Thread - 20"
[20:29:02 WARN]: org.apache.commons.lang.UnhandledException: Plugin KOLEC v69 greg generated an exception while executing task 14
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Player can not be null!
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
        at pl.kacperduras.protocoltab.manager.ProtocolTab.update(ProtocolTab.java:56)
        at pl.kacperduras.protocoltab.manager.ProtocolTab.update(ProtocolTab.java:92)
        at api.Main.lambda$1(Main.java:115)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more`

**Comment by ScoreBoardDEV** [comment]
Dobra, działa już, wystarczyła instalacja innego pliba :)
